name: Main
on:
  push:
    branches: [master]
    paths-ignore: 
      - .github/**
  workflow_dispatch:

jobs:
  test-stage:
    uses: benexdrake/github_actions/.github/workflows/test.yml@main
    with:
      NODE_VERSION: 20
      
  build-stage:
    needs: test-stage
    uses: benexdrake/github_actions/.github/workflows/portfolio-build.yml@main
    with:
      NODE_VERSION: 20
      BUILD_FOLDER: '.next'
    secrets:
      ABOUTME: ${{secrets.ABOUTME}}
      GH_USER: ${{secrets.GH_USER}}
      GH_SECRET: ${{secrets.GH_SECRET}}
      MONGO: ${{secrets.MONGO}}
      NEXTAUTH_URL: ${{secrets.NEXTAUTH_URL}}
      PROTECT_API: ${{secrets.PROTECT_API}}
      DISCORD_CLIENT: ${{secrets.DISCORD_CLIENT}}
      DISCORD_SECRET: ${{secrets.DISCORD_SECRET}}
      
  deploy-stage:
    needs: build-stage
    uses: benexdrake/github_actions/.github/workflows/deploy.yml@main
    with:
      APP_NAME: Portfolio
      SERVER_PORT: 22
      DEPLOY_PATH: '/var/www/portfolio'
    secrets:
      IP: ${{secrets.SERVER_IP}}
      SSH: ${{secrets.SERVER_SSH_KEY}}
      USERNAME: ${{secrets.SERVER_USERNAME}}
      PASSWORD: ${{secrets.SERVER_PASSWORD}}
